name: skhan
favicon: null
layout_spectrum: 0.26016
typography_spectrum: 0.8727599
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Beta Testing Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a070e'
    - '#feffff'
    - '#3e5bff'
    - '#352e71'
    - '#6393ff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.6326165
purpose: []
