title: Beta Testing Grid
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8125
  brandStrength: 0.5035842
  lightness: 0.5
  brandColors:
    - '#040405'
    - '#E9FBFF'
    - '#ABA299'
    - '#1D21B3'
    - '#90BDF2'
  rhythmicContrast: 0.6326165
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: skhan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4283154
layout_spectrum: 0
